routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::view('/', 'home')->name('home');
Route::get('group', 'TeamGroupController@index')->name('group.index');
Route::post('group', 'TeamGroupController@store')->name('group.store');
Route::delete('group/regenerate', 'TeamGroupController@destroy')->name('group.reset');
Route::get('simulation', 'SimulationController@index')->name('simulation.index');
Route::post('simulation/group', 'SimulationController@group')->name('simulation.group');
Route::post('simulation/week', 'SimulationController@week')->name('simulation.week');
Route::delete('simulation/reset', 'SimulationController@reset')->name('simulation.reset');

app/Models/Match.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Match extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $guarded = ['id'];

    public function home()
    {
        return $this->belongsTo(Team::class, 'home_id');
    }

    public function guest()
    {
        return $this->belongsTo(Team::class, 'guest_id');
    }
}

app/Models/Team.php
<?php

namespace App\Models;

use App\Services\Prediction;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    /** Mutators */
    public function getPointsAttribute()
    {
        return $this->wins * 3 + $this->draws;
    }

    public function getWinsAttribute()
    {
        return Match::query()->where(function ($builder) {
                /** @var Builder $builder */
                $builder->where('home_id', $this->id)->whereColumn('home_score', '>', 'guest_score');
            })->orWhere(function ($builder) {
                /** @var Builder $builder */
                $builder->where('guest_id', $this->id)->whereColumn('guest_score', '>', 'home_score');
            })->count();
    }

    public function getDrawsAttribute()
    {
        return Match::query()->where(function ($builder) {
            /** @var Builder $builder */
            $builder->where('home_id', $this->id)->whereColumn('home_score', '=', 'guest_score');
        })->orWhere(function ($builder) {
            /** @var Builder $builder */
            $builder->where('guest_id', $this->id)->whereColumn('guest_score', '=', 'home_score');
        })->count();
    }

    public function getLossAttribute()
    {
        return Match::query()->where(function ($builder) {
            /** @var Builder $builder */
            $builder->where('home_id', $this->id)->whereColumn('home_score', '<', 'guest_score');
        })->orWhere(function ($builder) {
            /** @var Builder $builder */
            $builder->where('guest_id', $this->id)->whereColumn('guest_score', '<', 'home_score');
        })->count();
    }

    public function getGoalsDifferentAttribute()
    {
        return Match::query()->where('home_id', $this->id)->sum('home_score') +
            Match::query()->where('guest_id', $this->id)->sum('guest_score')
            - Match::query()->where('home_id', $this->id)->sum('guest_score')
            - Match::query()->where('guest_id', $this->id)->sum('home_score');
    }

    public function getProdictionsAttribute()
    {
        $prediction = new Prediction($this);

        return $prediction->calculate();
    }

    public function morePointsWhen(Team $team)
    {
        return $this->points > $team->points;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SimulationController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\SimulateMatch;
use App\Models\Match;
use App\Models\Team;

class SimulationController extends Controller
{
    public function index()
    {
        $teams = Team::query()->where('in_league', true)->get()->sortBy([
            ['points', 'desc'],
            ['wins', 'desc'],
            ['goals_different', 'desc']
        ]);
        $weeklyMatches = Match::query()->with(['guest', 'home'])->whereNull('home_score')->limit(2)->orderBy('date')->get();
        $currentWeek = Match::query()->whereNotNull('home_score')->count() / 2 + 1;
        $matches = collect([]);

        if (request()->get('show_results', false) == true) {
            $matches = Match::all()->sortBy('date');
        }

        return view('simulation', compact('teams', 'weeklyMatches', 'currentWeek', 'matches'));
    }

    public function group()
    {
        Match::query()
            ->whereNull('home_score')
            ->get()
            ->each(fn(Match $match) => dispatch(new SimulateMatch($match)));

        return redirect()->route('simulation.index', ['show_results' => true]);
    }

    public function week()
    {
        $weekDate = now()->setTime(21, 0);

        Match::query()
            ->whereNull('home_score')
            ->whereDate('date', '>=', $weekDate)
            ->limit(2)
            ->get()
            ->each(fn(Match $match) => dispatch(new SimulateMatch($match)));

        return redirect()->route('simulation.index');
    }

    public function reset()
    {
        Match::query()
            ->whereNotNull('home_score')
            ->update(['home_score' => null, 'guest_score' => null]);

        return redirect()->route('simulation.index');
    }
}

app/Http/Controllers/TeamGroupController.php
<?php

namespace App\Http\Controllers;

use App\Events\TeamGroupCreated;
use App\Http\Requests\TeamGroupRequest;
use App\Models\Match;
use App\Models\Team;

class TeamGroupController extends Controller
{
    public function index()
    {
        $matches = Match::query()->with(['guest', 'home'])->get()->groupBy('date');

        return view('group', compact('matches'));
    }

    public function store(TeamGroupRequest $request)
    {
        Team::query()->whereIn('id', $request->get('teams'))->update(['in_league' => true]);

        event(new TeamGroupCreated($request->get('teams')));

        return redirect()->route('group.index');
    }

    public function destroy()
    {
        Team::query()->update(['in_league' => false]);

        Match::query()->delete();

        return redirect()->route('home');
    }
}

resources/views/group.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row">
            @foreach($matches as $date => $groups)
                <table class="table col-3 ml-5">
                    <thead class="thead-dark">
                    <tr>
                        <th colspan="3" scope="col" style="text-align: center;">Week {{ $loop->index + 1 }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($groups as $match)
                        <tr>
                            <td>{{ $match->home->name }}</td>
                            <td>-</td>
                            <td>{{ $match->guest->name }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @endforeach
        </div>

        <a href="{{ route('simulation.index') }}" class="btn btn-primary">Start simulation</a>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.main')

@section('content')
    <div class="jumbotron">
        <h1 class="display-4">Hello, mortal!</h1>
        <p class="lead">Do you want to bet on sports and earn some money? I will help you with this!</p>
        <hr class="my-4">
        <p>Select 4 team in one group which and let's imaging the game!</p>

        <form action="{{ route('group.store') }}" method="post">
            @csrf
            @foreach($teams as $team)
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="{{ $team->id }}" id="team{{ $team->id }}" name="teams[]">
                    <label class="form-check-label" for="team{{ $team->id }}">
                        {{ $team->name }}
                    </label>
                </div>
            @endforeach
            <p class="lead">
                <button class="btn btn-primary btn-lg" type="submit">Let's go!</button>
            </p>
        </form>
    </div>
@endsection

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Baba Vanga UEFA predictions</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>

<header>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <!-- Uploaded to SVGRepo https://www.svgrepo.com -->
                    <g id="🔍-Product-Icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="ic_fluent_predictions_24_filled" fill="#ffffff" fill-rule="nonzero">
                            <path d="M16.6824728,14.9260432 L17.967289,18.7801589 C18.2335628,19.5789337 17.8932573,20.4540914 17.1573198,20.8631617 C15.7855762,21.6256443 14.0642518,22 12,22 C9.93575073,22 8.214428,21.6256452 6.84268887,20.8631665 C6.10675341,20.4541035 5.76644595,19.5789539 6.03270398,18.7801798 L7.31752719,14.9260432 C8.61831898,15.9137899 10.2407011,16.5 12,16.5 C13.7592989,16.5 15.381681,15.9137899 16.6824728,14.9260432 Z M12,2 C13.3365841,2 14.5824347,2.38847636 15.630801,3.05867835 C15.5481783,3.37202292 15.4223719,3.60275432 15.2625631,3.76256313 C15.0100408,4.01508546 14.5804331,4.18270767 13.9379386,4.23364194 L13.71584,4.24625465 L13.3373016,4.2558579 C11.1679894,4.41468254 11.2222222,7.75 13.5,7.75 C14.3902073,7.75 14.9564755,7.9313492 15.2625631,8.23743687 C15.5150855,8.48995919 15.6827077,8.91956688 15.7336419,9.56206137 L15.7462547,9.78416001 L15.7558579,10.1626984 C15.8520715,11.4768355 17.1139805,11.9749857 18.093955,11.6571492 C17.007778,13.929649 14.6872766,15.5 12,15.5 C8.27207794,15.5 5.25,12.4779221 5.25,8.75 C5.25,5.02207794 8.27207794,2 12,2 Z M18.25,2 L18.25,2 C18.25,3.14960906 18.5198654,3.95920521 19.0303301,4.46966991 C19.5015283,4.9408681 20.2276077,5.20705858 21.2407227,5.24522281 L21.5,5.25 C22.4583333,5.25 22.4982639,6.62760417 21.6197917,6.74240451 L21.5,6.75 C20.3503909,6.75 19.5407948,7.01986538 19.0303301,7.53033009 C18.5591319,8.00152827 18.2929414,8.72760769 18.2547772,9.74072273 L18.25,10 C18.25,11 16.75,11 16.75,10 C16.75,8.85039094 16.4801346,8.04079479 15.9696699,7.53033009 C15.4984717,7.0591319 14.7723923,6.79294142 13.7592773,6.75477719 L13.5,6.75 C12.5416667,6.75 12.5017361,5.37239583 13.3802083,5.25759549 L13.5,5.25 C14.6496091,5.25 15.4592052,4.98013462 15.9696699,4.46966991 C16.4801346,3.95920521 16.75,3.14960906 16.75,2 L16.75,2 C16.75,1 18.25,1 18.25,2 Z" id="🎨-Color"></path>
                        </g>
                    </g>
                </svg>
                <strong>Baba Vanga UEFA predictions</strong>
            </a>
        </div>
    </div>
</header>

<main role="main">
    <div class="album py-5">
        <div class="container">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                @yield('content')
            </div>
        </div>
    </div>

</main>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

resources/views/simulation.blade.php
@extends('layouts.main')

@section('content')

    <div class="container">
        <div class="row">
            <table class="table col-8">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Team Name</th>
                    <th scope="col">P</th>
                    <th scope="col">W</th>
                    <th scope="col">D</th>
                    <th scope="col">L</th>
                    <th scope="col">GD</th>
                </tr>
                </thead>
                <tbody>
                @foreach($teams as $team)
                    <tr>
                        <th scope="row">{{ $team->name }}</th>
                        <td>{{ $team->points }}</td>
                        <td>{{ $team->wins }}</td>
                        <td>{{ $team->draws }}</td>
                        <td>{{ $team->loss }}</td>
                        <td>@if($team->goals_different <= 0) {{ $team->goals_different }} @else +{{ $team->goals_different }} @endif</td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            @if($weeklyMatches->count() > 0)
            <table class="table col-3 ml-5">
                <thead class="thead-dark">
                <tr>
                    <th colspan="3" scope="col" style="text-align: center;">Week {{ $currentWeek }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($weeklyMatches as $match)
                    <tr>
                        <td>{{ $match->home->name }}</td>
                        <td>-</td>
                        <td>{{ $match->guest->name }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @endif
        </div>
        <div class="row">
            @if($weeklyMatches->count() > 0)
                <div class="col-xs-6">
                    <form method="post" action="{{ route('simulation.group') }}" class="col-8 form-check-inline">
                        @csrf
                        <button type="submit" class="btn btn-success">Play all matches</button>
                    </form>
                </div>
                <div class="col-xs-6">
                    <form method="post" action="{{ route('simulation.week') }}" class="col-4">
                        @csrf
                        <button type="submit" class="btn btn-success">Play week matches</button>
                    </form>
                </div>
            @endif

            @if($weeklyMatches->count() == 0)
                    <div class="col-xs-6">
                        <form method="post" action="{{ route('simulation.reset') }}" class="col-8 form-check-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Reset results</button>
                        </form>
                    </div>

                    <div class="col-xs-6">
                        <form method="post" action="{{ route('group.reset') }}" class="col-8 mt-10">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Regenerate group</button>
                    </form>
                    </div>
            @endif
        </div>
    </div>

    @if($currentWeek > 3 && $weeklyMatches->count() > 0)
        <div class="container">
            <div class="row">
                <table class="table col-12">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Championship Prodictions</th>
                        <th scope="col">%</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($teams as $team)
                        <tr>
                            <th scope="row">{{ $team->name }}</th>
                            <td>{{ $team->prodictions }}%</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif

    @if($matches->count() > 0)
        <div class="container">
            <div class="row">
                <table class="table col-6" style="margin-top: 20px;">
                    <thead class="thead-dark">
                    <tr>
                        <th colspan="4" scope="col" style="text-align: center;">All matches</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($matches as $match)
                        @if($loop->index % 2 == 0)
                            <tr>
                                <th colspan="4" scope="col" style="text-align: center;">Week {{ round(($loop->index + 1) / 2) }}</th>
                            </tr>
                        @endif
                        <tr>
                            <td>{{ $match->home->name }}</td>
                            <td>-</td>
                            <td>{{ $match->guest->name }}</td>
                            <td>{{ $match->home_score }} - {{ $match->guest_score }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif

@endsection